version: 2


jobs:
  build_and_push:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker info
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t honestica/squid:3.5-${CIRCLE_WORKFLOW_ID} .
      - run: docker run -d -p 23128:3128 honestica/squid; sleep 10
      - run: curl --retry 10 --retry-delay 5 -v -s -L -x http://127.0.0.1:23128 -o /dev/null https://www.google.com
      - run: docker push honestica/hub:${CIRCLE_BRANCH}-${CIRCLE_WORKFLOW_ID}

workflows:
  version: 2
  common:
    jobs:
      - build_and_push